# backend/report_pptx.py
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN
import os
 
BLUE  = RGBColor(0x1F, 0x4E, 0x79)
LBLUE = RGBColor(0x2E, 0x75, 0xB6)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
LGRAY = RGBColor(0xF2, 0xF2, 0xF2)
 
 
def _add_text_box(slide, left, top, width, height, text, font_size=12, bold=False, color=None, bg_color=None):
    txBox = slide.shapes.add_textbox(Inches(left), Inches(top), Inches(width), Inches(height))
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    run = p.add_run()
    run.text = text
    run.font.size = Pt(font_size)
    run.font.bold = bold
    if color:
        run.font.color.rgb = color
    if bg_color:
        from pptx.oxml.ns import qn
        from lxml import etree
        sp = txBox._element
        spPr = sp.find(qn('p:spPr'))
        if spPr is None:
            spPr = etree.SubElement(sp, qn('p:spPr'))
        solidFill = etree.SubElement(spPr, qn('a:solidFill'))
        srgbClr = etree.SubElement(solidFill, qn('a:srgbClr'))
        srgbClr.set('val', f'{bg_color.red:02X}{bg_color.green:02X}{bg_color.blue:02X}')
    return txBox
 
 
def build_pptx(report_plan: dict, charts: list, output_path: str):
    prs = Presentation()
    prs.slide_width  = Inches(13.33)
    prs.slide_height = Inches(7.5)
 
    blank_layout = prs.slide_layouts[6]  # blank layout
 
    # ── Title slide ──────────────────────────────────────────
    slide = prs.slides.add_slide(blank_layout)
    bg = slide.background
    fill = bg.fill
    fill.solid()
    fill.fore_color.rgb = BLUE
 
    _add_text_box(slide, 1, 2, 11, 1.5, report_plan.get('report_title', 'Business Report'),
                  font_size=36, bold=True, color=WHITE)
    _add_text_box(slide, 1, 3.8, 11, 1, report_plan.get('executive_summary', ''),
                  font_size=14, color=RGBColor(0xBF, 0xD7, 0xED))
    _add_text_box(slide, 1, 6.8, 5, 0.4, 'Generated by CaseStudy Forge',
                  font_size=9, color=RGBColor(0x9D, 0xC3, 0xE6))
 
    # ── Content slides ───────────────────────────────────────
    chart_iter = iter(charts)
    for section in report_plan.get('sections', []):
        slide = prs.slides.add_slide(blank_layout)
 
        # Section title bar
        title_box = slide.shapes.add_shape(
            1,  # MSO_SHAPE_TYPE.RECTANGLE
            Inches(0), Inches(0), Inches(13.33), Inches(0.9)
        )
        title_box.fill.solid()
        title_box.fill.fore_color.rgb = LBLUE
        title_box.line.fill.background()
        _add_text_box(slide, 0.2, 0.05, 12, 0.8,
                      section.get('section_title', ''), font_size=18, bold=True, color=WHITE)
 
        chart_data = next(chart_iter, None)
        has_chart = chart_data and chart_data.get('png_path') and os.path.exists(chart_data['png_path'])
 
        # Narrative (left or full width depending on chart)
        narr_width = 5.8 if has_chart else 12
        _add_text_box(slide, 0.3, 1.1, narr_width, 4,
                      section.get('narrative', ''), font_size=11)
 
        if has_chart:
            slide.shapes.add_picture(chart_data['png_path'],
                                     Inches(6.5), Inches(1.0), Inches(6.5), Inches(4.0))
            _add_text_box(slide, 6.5, 5.1, 6.5, 0.6,
                          chart_data.get('insight_caption', ''),
                          font_size=9, color=RGBColor(0x59, 0x59, 0x59))
 
        # Callout
        callout = section.get('callout', {})
        if callout.get('text'):
            cb = slide.shapes.add_shape(1, Inches(0.3), Inches(5.4), Inches(5.8), Inches(0.8))
            cb.fill.solid()
            cb.fill.fore_color.rgb = RGBColor(0xD6, 0xE4, 0xF0)
            cb.line.fill.background()
            _add_text_box(slide, 0.4, 5.4, 5.6, 0.8,
                          f"{callout.get('label','KEY INSIGHT')}: {callout.get('text','')}",
                          font_size=9.5, color=BLUE)
 
    # ── Conclusion slide ─────────────────────────────────────
    slide = prs.slides.add_slide(blank_layout)
    title_box = slide.shapes.add_shape(1, Inches(0), Inches(0), Inches(13.33), Inches(0.9))
    title_box.fill.solid()
    title_box.fill.fore_color.rgb = BLUE
    title_box.line.fill.background()
    _add_text_box(slide, 0.2, 0.05, 12, 0.8, 'Conclusion', font_size=18, bold=True, color=WHITE)
    _add_text_box(slide, 0.5, 1.2, 12, 5, report_plan.get('conclusion', ''), font_size=12)
 
    prs.save(output_path)
    return output_path
